# Site settings
title: Stephanie Osan
email: stephanieosan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stephanie Osan is a designer creating educational experiences from the mountains of Colorado.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Stephanie Osan
twitter_username: stephosan
github_username: stephanieosan
address:
  - line: PO Box 2161
  - line: Telluride, CO
  # Feel free to add more lines here 
telephone: 
copyright: 2016

# API settings
google_api_key:

# Build settings
markdown: kramdown